### ISSUE TITLE
Exception Value: 'RelatedManager' object is not iterable -- when attempting to leave event (or when forcibly removed)

### ISSUE THREAD

**Issue by kythre** [MarkMichon1/groupbuyorganizer2#1]
When I try to leave an event I get an error page with this:

```
Environment:


Request Method: GET
Request URL: https://www.pyrogroupbuys.com/events/6294735a-7646-46c1-981b-f311138f9227/leave/

Django Version: 3.0.8
Python Version: 3.8.2
Installed Applications:
['captcha',
 'crispy_forms',
 'google_analytics',
 'mathfilters',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'events',
 'general',
 'users']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mark7/gb/events/views.py", line 122, in leave_event
    for commit in membership.split_commits:

Exception Type: TypeError at /events/6294735a-7646-46c1-981b-f311138f9227/leave/
Exception Value: 'RelatedManager' object is not iterable
```

**Comment by MarkMichon1** [comment]
Fixed.
