### ISSUE TITLE
Exception Value: division by zero -- when trying to view My Order

### ISSUE THREAD

**Issue by kythre** [MarkMichon1/groupbuyorganizer2#3]
I created a new event then clicked "My Order". Obviously only happens when my order is empty and can be circumvented (on my side) by actually adding to my order

```
Environment:


Request Method: GET
Request URL: https://www.pyrogroupbuys.com/events/6294735a-7646-46c1-981b-f311138f9227/my-order/002b5485-5eba-4786-b130-d1fcaa275993/

Django Version: 3.0.8
Python Version: 3.8.2
Installed Applications:
['captcha',
 'crispy_forms',
 'google_analytics',
 'mathfilters',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'events',
 'general',
 'users']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mark7/gb/events/views.py", line 601, in my_order
    my_order_data = event.generate_event_pages_contents(page_type='my_order', membership=targetted_membership)
  File "/home/mark7/gb/events/models.py", line 139, in generate_event_pages_contents
    my_order_summary = self.generate_user_totals_all(target_membership=membership)
  File "/home/mark7/gb/events/models.py", line 155, in generate_user_totals_all
    percentage_of_event = pre_total / grand_total

Exception Type: ZeroDivisionError at /events/6294735a-7646-46c1-981b-f311138f9227/my-order/002b5485-5eba-4786-b130-d1fcaa275993/
Exception Value: division by zero
```

**Comment by MarkMichon1** [comment]
Fixed!
