### ISSUE TITLE
Exception Value: get() returned more than one EventMembership -- it returned 2! --- when adding myself

### ISSUE THREAD

**Issue by kythre** [MarkMichon1/groupbuyorganizer2#5]
I added myself to a event I created and caused this error every time I try to load up anything from that event.
Also it appears to load the event twice however I'm not shown as an organizer for one of them. They both have the same ID in the URL when I try to load them
[Image](https://i.imgur.com/jVtctD8.png)

```Environment:


Request Method: GET
Request URL: https://www.pyrogroupbuys.com/events/d4f40d80-2298-49ca-b1af-60e098f8c464/

Django Version: 3.0.8
Python Version: 3.8.2
Installed Applications:
['captcha',
 'crispy_forms',
 'google_analytics',
 'mathfilters',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'events',
 'general',
 'users']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mark7/gb/events/views.py", line 37, in event
    event, membership, is_valid = event_auth_checkpoint(event_id=event_id, request=request)
  File "/home/mark7/gb/events/view_utilities.py", line 16, in event_auth_checkpoint
    membership = EventMembership.objects.get(user=request.user, event=event)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/db/models/query.py", line 419, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /events/d4f40d80-2298-49ca-b1af-60e098f8c464/
Exception Value: get() returned more than one EventMembership -- it returned 2!
```

**Comment by MarkMichon1** [comment]
I have to admit.... you are very good at breaking things lol.  Fixed.
