### ISSUE TITLE
Input Filtering

### ISSUE THREAD

**Issue by kythre** [MarkMichon1/groupbuyorganizer2#6]
- The item name character limit seems excessive (can overrun the screen)
- You can input negatives into number fields
- You entering a zero into number fields (at least the case size field) causes the entire event to error out

```
Environment:


Request Method: GET
Request URL: https://www.pyrogroupbuys.com/events/27fd94d2-293f-4ab8-9aa1-b9cf46be38b0/

Django Version: 3.0.8
Python Version: 3.8.2
Installed Applications:
['captcha',
 'crispy_forms',
 'google_analytics',
 'mathfilters',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'events',
 'general',
 'users']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mark7/gb/events/views.py", line 40, in event
    event_data = event.generate_event_pages_contents(page_type='event', membership=membership)
  File "/home/mark7/gb/events/models.py", line 94, in generate_event_pages_contents
    item_view = item.render_event_view(membership=membership)
  File "/home/mark7/gb/events/models.py", line 227, in render_event_view
    returned_dict = {**returned_dict, **self._core_data_fragment()}
  File "/home/mark7/gb/events/models.py", line 260, in _core_data_fragment
    new_dict['piece_price'] = round((self.price/self.packing), 2)

Exception Type: DivisionByZero at /events/27fd94d2-293f-4ab8-9aa1-b9cf46be38b0/
Exception Value: [<class 'decimal.DivisionByZero'>]
```

- When doing an excessive case split I can cause a temporary error
[Image](https://i.imgur.com/Af0hmj5.png)
```
Environment:


Request Method: POST
Request URL: https://www.pyrogroupbuys.com/events/abbb8e18-1a45-42bc-9892-8932358fcbfa/item/1727de69-cbd2-4bad-a972-f328835d55d9/

Django Version: 3.0.8
Python Version: 3.8.2
Installed Applications:
['captcha',
 'crispy_forms',
 'google_analytics',
 'mathfilters',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'events',
 'general',
 'users']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mark7/gb/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
    raise ValueError(

Exception Type: ValueError at /events/abbb8e18-1a45-42bc-9892-8932358fcbfa/item/1727de69-cbd2-4bad-a972-f328835d55d9/
Exception Value: The view events.views.item didn't return an HttpResponse object. It returned None instead.
```

**Comment by MarkMichon1** [comment]
Good stuff, this simply needs a validator added into the 'packing' IntegerField in the Item model.

**Comment by MarkMichon1** [comment]
Excluding the length of the item name which needs manual DB actions done, the rest has been fixed!
